name: Release Preview

on:
  pull_request:
    types: [opened, edited, labeled, synchronize]

jobs:
  release-preview:
    if: >
      startsWith(github.event.pull_request.title, 'chore(release)') &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install standard-version
        run: npm install standard-version

      - name: Run standard-version (dry run) and save output
        run: |
          npx standard-version --dry-run > release-output.txt

      - name: Post comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "$(cat release-output.txt)"
