name: Create Release.
run-name: Create Release from branch ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'If you want to run the workflow without making any changes'
        required: true
        default: 'true'
        type: choice
        options:
        - true
        - false

jobs:
  create_patch_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        npm install standard-version  

    - name: Create release/maintenance branch
      run: |
        git config --global user.email "release_githubactions@github.com"
        git config --global user.name "Release GitHub Action"

        dry=${{ github.event.inputs.dry_run }}
        if [ "$dry" == "true" ]; then
          dry="echo"
          echo "# Note: This script is executed in dry-run mode and will not perform the git-push"
        else
          dry=""
        fi

        rc_branch=${{ github.ref_name }}
        release_branch_name=${rc_branch//rc/release}
        echo "release_branch_name=$release_branch_name" >> $GITHUB_ENV
        release_version=${release_branch_name/release\//}
        echo "release_version=$release_version" >> $GITHUB_ENV

        git checkout -b $release_branch_name
        $dry git push -u origin $release_branch_name
        
        if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
          npm run release -- --dry-run
        else
          npm run release
          git push --follow-tags
        fi

    - name: Create Pull Request
      id: create_pr
      run: |
        release_branch_name=${{ env.release_branch_name }}
        if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
          echo "Dry run mode enabled. Skipping pull request creation."
        else
          gh pr create --base main --head $release_branch_name --title "Release ${{ env.release_version }}" --body "This PR merges the release branch $release_branch_name into main."
        fi
