name: Create Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  create_release:
    runs-on: ubuntu-22.04
    if: startsWith(github.event.head_commit.message, 'chore(release)') && !github.event.act
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        npm install standard-version
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "Release GitHub Action"
    - name: Create Release
      run: |
        npm run release