name: Patch Release Candidate

on:
 push:
   branches:
     - rc/*
   tags-ignore:
     - "*"

jobs: 
  patch_rc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        npm install standard-version
    - name: Configure Git
      run: |
        git config --global user.email "githubactions_rc@github.com"
        git config --global user.name "GitHub Action RC"
    - name: Release new RC version
      run: |
        TAG="v$(jq '.version' package.json -r)"

        if `git log -1 --pretty=%B | grep -E "^(feat:|fix:|chore: trigger)" &>/dev/null`; then
          echo "Detected "feat"/"fix"/"chore: trigger" commits. Running standard-version..."
          npm run release -- --prerelease rc
          git push --follow-tags
        else
          echo "No feat/fix commits since '$TAG'. Skipping version bump."
        fi
