name: Patch Release Candidate

on:
 push:
   branches:
     - rc/*
   tags-ignore:
     - "*"

jobs: 
  patch_rc:
    if: > 
      contains(github.event.head_commit.message, 'feat:') || 
      contains(github.event.head_commit.message, 'fix:') || 
      contains(github.event.head_commit.message, 'chore: trigger')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        npm install standard-version
    - name: Configure Git
      run: |
        git config --global user.email "githubactions_rc@github.com"
        git config --global user.name "GitHub Action RC"
    - name: Release new RC version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Detected "feat"/"fix"/"chore: trigger" commits. Running standard-version..."
        npm run release -- --prerelease rc --skip.changelog 
        git push --follow-tags
        TAG="v$(jq '.version' package.json -r)"
        gh release create "$TAG" --title="Release: $TAG" --notes="Automated release for $TAG" --latest=false -p