name: Pull request update

on:
    push:
        branches:
            - main

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Update ALL THE PRS! 🎉
          uses: castastrophe/actions-pr-auto-update