name: Pull request update

on:
  push:
    branches:
      - main
permissions:
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Who am I?
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token ${{ env.GITHUB_TOKEN }}" https://api.github.com/user
      - name: Update ALL THE PRS! 🎉
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: castastrophe/actions-pr-auto-update@v1.1.0

