name: Pull request update

on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: read

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update ALL THE PRS! 🎉
        with:
          token: ${{ secrets.PR_UPDATE_TOKEN }}
        uses: castastrophe/actions-pr-auto-update@v1.1.0

