name: Release Please
on:
  push:
    branches:
      - main
      - rc  # 👈 Add this line
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: "node"
          package-name: "releases-test"
          prerelease: ${{ contains(github.ref, 'rc') }}  # 👈 Automatically enable RCs in the rc branch
          command: "github"  # Default behavior (release PRs)
