on:
  push:
    branches:
      - main
      - rc/*

permissions:
  contents: write
  pull-requests: write

name: release-please-rc
description: Create a release candidate (RC) for the release-please action

jobs:
  release-please-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: release-please-config-rc.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json